org.gradle.jvmargs=-Xmx8G
org.gradle.java.installations.paths=D:/SSS/JDK/zulu17.58.21-ca-jdk17.0.15-win_x64,D:/SSS/JDK/zulu21.42.19-ca-jdk21.0.7-win_x64,D:/SSS/JDK/zulu24.30.11-ca-jdk24.0.1-win_x64,D:/SSS/JDK/zulu25.30.17-ca-jdk25.0.1-win_x64
org.gradle.parallel=false
org.gradle.workers.max=32
org.gradle.daemon=true
org.gradle.caching=true
org.gradle.configureondemand=true

mod_archives_base_name=litematica-printer
mod_id=litematica-printer
mod_wrapper_id=litematica-printer-wrapper
mod_license=AGPL-3.0
mod_name=litematica-printer-EMT
mod_version=EMT

loader_version=0.18.4
pinyin_version=2.5.1

# https://mvnrepository.com/artifact/org.projectlombok/lombok
lombok_version=1.18.42
