minecraft_dependency=>=26.1 <=26.1.2
minecraft_version=26.1.2

# Versions installed in D:\PCL2\.minecraft\versions\26.1.2-Fabric 0.19.3
fabric_version=0.155.2+26.1.2
malilib=malilib-fabric-26.1.2:0.28.9
malilib_dependency=0.28.9
litematica=litematica-fabric-26.1.2:0.27.10
litematica_dependency=0.27.10
tweakeroo=tweakeroo-fabric-26.1.2:0.28.6
tweakeroo_dependency=0.28.6

quickshulker=https://github.com/EnderPhantomWing/quickshulker-multi/releases/download/3.2.7/quickshulker-v3.2.7-mc26.1.2-200-43d8da4-release.jar
chesttracker=2.8.1-beta.5+26.1
whereisit=2.7.3-beta.3+26.1
jackfredlib=0.10.6+26.1
searchables=Searchables-fabric-26.1:1.0.4
yacl=3.9.1+26.1-fabric
modmenu=18.0.0
