minecraft_dependency=>=26.2
minecraft_version=26.2

# Versions installed in D:\PCL2\.minecraft\versions\26.2-Fabric 0.19.3
fabric_version=0.161.0+26.2
malilib=malilib-fabric-26.2:0.29.6
malilib_dependency=0.29.6
litematica=litematica-fabric-26.2:0.28.8
litematica_dependency=0.28.8
tweakeroo=tweakeroo-fabric-26.2:0.29.5
tweakeroo_dependency=0.29.5

modmenu=20.0.2